name: Python CICD Pipeline

# This defines the trigger
on:
  pull_request: 
    branches:
     - develop # Trigger only when a PR is raised against develop

jobs:
   test-code:
     runs-on: ubuntu-latest # mention your virtual machine (OS) here

     steps:
      - name: Checkout code
        uses: actions/checkout@v4 # This checks out your code so that the workflow can access it

      - name: Set up Python
        uses: actions/setup-python@v4 # This sets up the Python environments 
        with:
         python-version: '3.12'
         
      - name: Run Python Script
        run: |
          # This simply runs your file to make sure there are no errors 
          python sample.py